name: Update V2Ray Subscription

on:
  schedule:
    - cron: '0 2 * * *'   # 每天自动跑一次
  workflow_dispatch:     # 允许你手动点

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.9'

      - run: pip install -r requirements.txt

      - run: python merge.py

      - run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add sub.txt
          git commit -m "auto update subscription" || true
          git push

