name: Update V2Ray Subscription

on:
  schedule:
    - cron: '0 8 * * *'   # 每天凌晨 8 点自动运行（你可以按需要调整）
  workflow_dispatch:     # 允许你手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python merge.py

      - run: |
          git config user.name "RyanLee94"
          git config user.email "ryan_lry@icloud.com"
          git add sub.txt
          git commit -m "auto update subscription" || true
          git push
